//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CustomInterfaces
{
    [Serializable]
    public class GetAnglesResponse : Message
    {
        public const string k_RosMessageName = "custom_interfaces/GetAngles";
        public override string RosMessageName => k_RosMessageName;

        public float left_wheel_angle;
        public float right_wheel_angle;

        public GetAnglesResponse()
        {
            this.left_wheel_angle = 0.0f;
            this.right_wheel_angle = 0.0f;
        }

        public GetAnglesResponse(float left_wheel_angle, float right_wheel_angle)
        {
            this.left_wheel_angle = left_wheel_angle;
            this.right_wheel_angle = right_wheel_angle;
        }

        public static GetAnglesResponse Deserialize(MessageDeserializer deserializer) => new GetAnglesResponse(deserializer);

        private GetAnglesResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.left_wheel_angle);
            deserializer.Read(out this.right_wheel_angle);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.left_wheel_angle);
            serializer.Write(this.right_wheel_angle);
        }

        public override string ToString()
        {
            return "GetAnglesResponse: " +
            "\nleft_wheel_angle: " + left_wheel_angle.ToString() +
            "\nright_wheel_angle: " + right_wheel_angle.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
