//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CustomInterfaces
{
    [Serializable]
    public class GetAnglesRequest : Message
    {
        public const string k_RosMessageName = "custom_interfaces/GetAngles";
        public override string RosMessageName => k_RosMessageName;

        public bool request_both_angles;

        public GetAnglesRequest()
        {
            this.request_both_angles = false;
        }

        public GetAnglesRequest(bool request_both_angles)
        {
            this.request_both_angles = request_both_angles;
        }

        public static GetAnglesRequest Deserialize(MessageDeserializer deserializer) => new GetAnglesRequest(deserializer);

        private GetAnglesRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.request_both_angles);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request_both_angles);
        }

        public override string ToString()
        {
            return "GetAnglesRequest: " +
            "\nrequest_both_angles: " + request_both_angles.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
