//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CustomInterfaces
{
    [Serializable]
    public class PatrolResult : Message
    {
        public const string k_RosMessageName = "custom_interfaces/Patrol";
        public override string RosMessageName => k_RosMessageName;

        // Result
        public bool success;

        public PatrolResult()
        {
            this.success = false;
        }

        public PatrolResult(bool success)
        {
            this.success = success;
        }

        public static PatrolResult Deserialize(MessageDeserializer deserializer) => new PatrolResult(deserializer);

        private PatrolResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "PatrolResult: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
