//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CustomInterfaces
{
    [Serializable]
    public class PatrolFeedback : Message
    {
        public const string k_RosMessageName = "custom_interfaces/Patrol";
        public override string RosMessageName => k_RosMessageName;

        // Feedback
        public float time_left;

        public PatrolFeedback()
        {
            this.time_left = 0.0f;
        }

        public PatrolFeedback(float time_left)
        {
            this.time_left = time_left;
        }

        public static PatrolFeedback Deserialize(MessageDeserializer deserializer) => new PatrolFeedback(deserializer);

        private PatrolFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.time_left);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.time_left);
        }

        public override string ToString()
        {
            return "PatrolFeedback: " +
            "\ntime_left: " + time_left.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
