//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CustomInterfaces
{
    [Serializable]
    public class PatrolGoal : Message
    {
        public const string k_RosMessageName = "custom_interfaces/Patrol";
        public override string RosMessageName => k_RosMessageName;

        // Goal
        public float radius;

        public PatrolGoal()
        {
            this.radius = 0.0f;
        }

        public PatrolGoal(float radius)
        {
            this.radius = radius;
        }

        public static PatrolGoal Deserialize(MessageDeserializer deserializer) => new PatrolGoal(deserializer);

        private PatrolGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.radius);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.radius);
        }

        public override string ToString()
        {
            return "PatrolGoal: " +
            "\nradius: " + radius.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
