//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ExampleInterfaces
{
    [Serializable]
    public class GetWheelsRequest : Message
    {
        public const string k_RosMessageName = "example_interfaces/GetWheels";
        public override string RosMessageName => k_RosMessageName;

        public bool request_both_angles;

        public GetWheelsRequest()
        {
            this.request_both_angles = false;
        }

        public GetWheelsRequest(bool request_both_angles)
        {
            this.request_both_angles = request_both_angles;
        }

        public static GetWheelsRequest Deserialize(MessageDeserializer deserializer) => new GetWheelsRequest(deserializer);

        private GetWheelsRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.request_both_angles);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request_both_angles);
        }

        public override string ToString()
        {
            return "GetWheelsRequest: " +
            "\nrequest_both_angles: " + request_both_angles.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
