//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Turtlebot3
{
    [Serializable]
    public class GetAngleRequest : Message
    {
        public const string k_RosMessageName = "turtlebot3_msgs/GetAngle";
        public override string RosMessageName => k_RosMessageName;

        //  GetAngle.srv
        public string wheel_name;
        //  Name of the wheel (e.g., 'left_wheel', 'right_wheel')

        public GetAngleRequest()
        {
            this.wheel_name = "";
        }

        public GetAngleRequest(string wheel_name)
        {
            this.wheel_name = wheel_name;
        }

        public static GetAngleRequest Deserialize(MessageDeserializer deserializer) => new GetAngleRequest(deserializer);

        private GetAngleRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.wheel_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.wheel_name);
        }

        public override string ToString()
        {
            return "GetAngleRequest: " +
            "\nwheel_name: " + wheel_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
