//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Turtlebot3
{
    [Serializable]
    public class GetAngleResponse : Message
    {
        public const string k_RosMessageName = "turtlebot3_msgs/GetAngle";
        public override string RosMessageName => k_RosMessageName;

        public float angle;
        //  Angle of the corresponding wheel

        public GetAngleResponse()
        {
            this.angle = 0.0f;
        }

        public GetAngleResponse(float angle)
        {
            this.angle = angle;
        }

        public static GetAngleResponse Deserialize(MessageDeserializer deserializer) => new GetAngleResponse(deserializer);

        private GetAngleResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.angle);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.angle);
        }

        public override string ToString()
        {
            return "GetAngleResponse: " +
            "\nangle: " + angle.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
