//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Turtlebot3
{
    [Serializable]
    public class SoundRequest : Message
    {
        public const string k_RosMessageName = "turtlebot3_msgs/Sound";
        public override string RosMessageName => k_RosMessageName;

        // #######################################
        //  CONSTANTS
        // #######################################
        //  uint8 OFF           = 0
        //  uint8 ON            = 1
        //  uint8 LOW_BATTERY   = 2
        //  uint8 ERROR         = 3
        //  uint8 BUTTON1       = 4
        //  uint8 BUTTON2       = 5
        public byte value;

        public SoundRequest()
        {
            this.value = 0;
        }

        public SoundRequest(byte value)
        {
            this.value = value;
        }

        public static SoundRequest Deserialize(MessageDeserializer deserializer) => new SoundRequest(deserializer);

        private SoundRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "SoundRequest: " +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
